CREATE DATABASE IF NOT EXISTS heat_monitor
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;

USE heat_monitor;

CREATE TABLE IF NOT EXISTS readings (
  id INT AUTO_INCREMENT PRIMARY KEY,
  timestamp DATETIME NOT NULL,
  s1 FLOAT DEFAULT 0,
  s2 FLOAT DEFAULT 0,
  s3 FLOAT DEFAULT 0,
  s4 FLOAT DEFAULT 0
);
